# fly.toml app configuration file generated for libri-backend on 2024-10-22T19:11:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'libri-backend'
primary_region = 'otp'

[build]

[env]
  DATABASE_URL = 'mysql://root:bookstore123@bookstore-database.fly.dev:3306/bookstore_db'
  PORT = '8080'
  SECRET_KEY = 'secret'
  SMTP_PASSWORD = 'aptr mxzc gnnn ovim'
  SMTP_USERNAME = 'bookstore.project01@gmail.com'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
